# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kniffel_gui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(547, 558)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QtCore.QRect(10, 70, 551, 291))
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(19)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.Dense4Pattern)
        item.setBackground(brush)
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.Dense4Pattern)
        item.setBackground(brush)
        self.tableWidget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.Dense4Pattern)
        item.setBackground(brush)
        self.tableWidget.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.Dense5Pattern)
        item.setBackground(brush)
        self.tableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.Dense5Pattern)
        item.setBackground(brush)
        self.tableWidget.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.Dense5Pattern)
        item.setBackground(brush)
        self.tableWidget.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 2, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.Dense4Pattern)
        item.setBackground(brush)
        self.tableWidget.setItem(16, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.Dense4Pattern)
        item.setBackground(brush)
        self.tableWidget.setItem(16, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.Dense4Pattern)
        item.setBackground(brush)
        self.tableWidget.setItem(16, 2, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.Dense4Pattern)
        item.setBackground(brush)
        self.tableWidget.setItem(17, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.Dense4Pattern)
        item.setBackground(brush)
        self.tableWidget.setItem(17, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.Dense4Pattern)
        item.setBackground(brush)
        self.tableWidget.setItem(17, 2, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.Dense5Pattern)
        item.setBackground(brush)
        self.tableWidget.setItem(18, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.Dense5Pattern)
        item.setBackground(brush)
        self.tableWidget.setItem(18, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.Dense5Pattern)
        item.setBackground(brush)
        self.tableWidget.setItem(18, 2, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(128)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setVisible(True)
        self.roll_btn = QtWidgets.QPushButton(self.centralwidget)
        self.roll_btn.setGeometry(QtCore.QRect(6, 465, 106, 32))
        self.roll_btn.setObjectName("roll_btn")
        self.first_roll = QtWidgets.QPushButton(self.centralwidget)
        self.first_roll.setEnabled(True)
        self.first_roll.setGeometry(QtCore.QRect(10, 380, 50, 46))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.first_roll.setFont(font)
        self.first_roll.setStyleSheet("#first_roll{\n"
"background-color: transparent;\n"
"border-image: url(:1.png);\n"
"background: none;\n"
"background-repeat: none;\n"
"}\n"
"#first_roll:pressed\n"
"{\n"
"    border-image: url(:1_pressed.png);\n"
"}")
        self.first_roll.setText("")
        self.first_roll.setAutoDefault(False)
        self.first_roll.setDefault(False)
        self.first_roll.setFlat(False)
        self.first_roll.setObjectName("first_roll")
        self.second_roll = QtWidgets.QPushButton(self.centralwidget)
        self.second_roll.setGeometry(QtCore.QRect(80, 380, 51, 46))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.second_roll.setFont(font)
        self.second_roll.setText("")
        self.second_roll.setAutoDefault(False)
        self.second_roll.setDefault(False)
        self.second_roll.setFlat(False)
        self.second_roll.setObjectName("second_roll")
        self.third_roll = QtWidgets.QPushButton(self.centralwidget)
        self.third_roll.setGeometry(QtCore.QRect(150, 380, 50, 46))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.third_roll.setFont(font)
        self.third_roll.setText("")
        self.third_roll.setObjectName("third_roll")
        self.fourth_roll = QtWidgets.QPushButton(self.centralwidget)
        self.fourth_roll.setEnabled(True)
        self.fourth_roll.setGeometry(QtCore.QRect(220, 380, 50, 46))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.fourth_roll.setFont(font)
        self.fourth_roll.setText("")
        self.fourth_roll.setDefault(False)
        self.fourth_roll.setFlat(False)
        self.fourth_roll.setObjectName("fourth_roll")
        self.fifth_roll = QtWidgets.QPushButton(self.centralwidget)
        self.fifth_roll.setGeometry(QtCore.QRect(290, 380, 50, 46))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.fifth_roll.setFont(font)
        self.fifth_roll.setText("")
        self.fifth_roll.setAutoDefault(False)
        self.fifth_roll.setDefault(False)
        self.fifth_roll.setFlat(False)
        self.fifth_roll.setObjectName("fifth_roll")
        self.np_button = QtWidgets.QPushButton(self.centralwidget)
        self.np_button.setGeometry(QtCore.QRect(130, 465, 131, 32))
        self.np_button.setObjectName("np_button")
        self.header = QtWidgets.QLabel(self.centralwidget)
        self.header.setGeometry(QtCore.QRect(30, -30, 451, 141))
        self.header.setObjectName("header")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 547, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "11"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "12"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "13"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "14"))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "15"))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "16"))
        item = self.tableWidget.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "17"))
        item = self.tableWidget.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "18"))
        item = self.tableWidget.verticalHeaderItem(18)
        item.setText(_translate("MainWindow", "19"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Würfe"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Spieler 1"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Spieler 2"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "Nur EINSER"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "Nur ZWEIER"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "Nur DREIER"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "Nur VIERER"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("MainWindow", "Nur FUENFER"))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(4, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("MainWindow", "Nur SECHSER"))
        item = self.tableWidget.item(5, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(5, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("MainWindow", "GESAMT ->"))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("MainWindow", "Bonus bei 63+"))
        item = self.tableWidget.item(7, 1)
        item.setText(_translate("MainWindow", "Plus 35 Pkt."))
        item = self.tableWidget.item(7, 2)
        item.setText(_translate("MainWindow", "Plus 35 Pkt."))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("MainWindow", "GESAMT + BONUS"))
        item = self.tableWidget.item(9, 0)
        item.setText(_translate("MainWindow", "Dreierpasch"))
        item = self.tableWidget.item(9, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(9, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(10, 0)
        item.setText(_translate("MainWindow", "Viererpasch"))
        item = self.tableWidget.item(10, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(10, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(11, 0)
        item.setText(_translate("MainWindow", "Fullhouse (25)"))
        item = self.tableWidget.item(11, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(11, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(12, 0)
        item.setText(_translate("MainWindow", "kleine Straße (30)"))
        item = self.tableWidget.item(12, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(12, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(13, 0)
        item.setText(_translate("MainWindow", "große Straße (40)"))
        item = self.tableWidget.item(13, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(13, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(14, 0)
        item.setText(_translate("MainWindow", "KNIFFEL (50)"))
        item = self.tableWidget.item(14, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(14, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(15, 0)
        item.setText(_translate("MainWindow", "Chance"))
        item = self.tableWidget.item(15, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(15, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(16, 0)
        item.setText(_translate("MainWindow", "ges. unt. Teil"))
        item = self.tableWidget.item(17, 0)
        item.setText(_translate("MainWindow", "ges. ob. Teil"))
        item = self.tableWidget.item(18, 0)
        item.setText(_translate("MainWindow", "GESAMT ->"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.roll_btn.setText(_translate("MainWindow", "Würfeln!!!!"))
        self.np_button.setText(_translate("MainWindow", "Nächster Spieler"))
        self.header.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:64pt; font-weight:600;\">KNIFFELLLLL!!!</span></p></body></html>"))
