# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setup_gui/setup_window.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Setup_Window(object):
    def setupUi(self, Setup_Window):
        Setup_Window.setObjectName("Setup_Window")
        Setup_Window.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Setup_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.player_count = QtWidgets.QSpinBox(self.centralwidget)
        self.player_count.setGeometry(QtCore.QRect(130, 10, 42, 22))
        self.player_count.setObjectName("player_count")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 131, 16))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(510, 470, 113, 32))
        self.pushButton.setDefault(True)
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 111, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 111, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 130, 111, 16))
        self.label_5.setObjectName("label_5")
        self.fcolor = QtWidgets.QComboBox(self.centralwidget)
        self.fcolor.setGeometry(QtCore.QRect(130, 67, 131, 31))
        self.fcolor.setObjectName("fcolor")
        self.fcolor.addItem("")
        self.fcolor.addItem("")
        self.fcolor.addItem("")
        self.fcolor.addItem("")
        self.fcolor.addItem("")
        self.fcolor.addItem("")
        self.fcolor.addItem("")
        self.fcolor.addItem("")
        self.tcolor = QtWidgets.QComboBox(self.centralwidget)
        self.tcolor.setGeometry(QtCore.QRect(130, 127, 131, 31))
        self.tcolor.setObjectName("tcolor")
        self.tcolor.addItem("")
        self.tcolor.addItem("")
        self.tcolor.addItem("")
        self.tcolor.addItem("")
        self.tcolor.addItem("")
        self.tcolor.addItem("")
        self.tcolor.addItem("")
        self.tcolor.addItem("")
        self.scolor = QtWidgets.QComboBox(self.centralwidget)
        self.scolor.setGeometry(QtCore.QRect(130, 97, 131, 31))
        self.scolor.setObjectName("scolor")
        self.scolor.addItem("")
        self.scolor.addItem("")
        self.scolor.addItem("")
        self.scolor.addItem("")
        self.scolor.addItem("")
        self.scolor.addItem("")
        self.scolor.addItem("")
        self.scolor.addItem("")
        Setup_Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Setup_Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        Setup_Window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Setup_Window)
        self.statusbar.setObjectName("statusbar")
        Setup_Window.setStatusBar(self.statusbar)

        self.retranslateUi(Setup_Window)
        QtCore.QMetaObject.connectSlotsByName(Setup_Window)

    def retranslateUi(self, Setup_Window):
        _translate = QtCore.QCoreApplication.translate
        Setup_Window.setWindowTitle(_translate("Setup_Window", "Setup_Window"))
        self.label.setText(_translate("Setup_Window", "How many Players?"))
        self.pushButton.setText(_translate("Setup_Window", "start Game"))
        self.label_3.setText(_translate("Setup_Window", "First throw color  :"))
        self.label_4.setText(_translate("Setup_Window", "2nd throw color   :"))
        self.label_5.setText(_translate("Setup_Window", "3rd throw color    :"))
        self.fcolor.setItemText(0, _translate("Setup_Window", "select color"))
        self.fcolor.setItemText(1, _translate("Setup_Window", "Red"))
        self.fcolor.setItemText(2, _translate("Setup_Window", "Green"))
        self.fcolor.setItemText(3, _translate("Setup_Window", "Blue"))
        self.fcolor.setItemText(4, _translate("Setup_Window", "Purple"))
        self.fcolor.setItemText(5, _translate("Setup_Window", "Brown"))
        self.fcolor.setItemText(6, _translate("Setup_Window", "Black"))
        self.fcolor.setItemText(7, _translate("Setup_Window", "Yellow"))
        self.tcolor.setItemText(0, _translate("Setup_Window", "select color"))
        self.tcolor.setItemText(1, _translate("Setup_Window", "Red"))
        self.tcolor.setItemText(2, _translate("Setup_Window", "Green"))
        self.tcolor.setItemText(3, _translate("Setup_Window", "Blue"))
        self.tcolor.setItemText(4, _translate("Setup_Window", "Purple"))
        self.tcolor.setItemText(5, _translate("Setup_Window", "Brown"))
        self.tcolor.setItemText(6, _translate("Setup_Window", "Black"))
        self.tcolor.setItemText(7, _translate("Setup_Window", "Yellow"))
        self.scolor.setItemText(0, _translate("Setup_Window", "select color"))
        self.scolor.setItemText(1, _translate("Setup_Window", "Red"))
        self.scolor.setItemText(2, _translate("Setup_Window", "Green"))
        self.scolor.setItemText(3, _translate("Setup_Window", "Blue"))
        self.scolor.setItemText(4, _translate("Setup_Window", "Purple"))
        self.scolor.setItemText(5, _translate("Setup_Window", "Brown"))
        self.scolor.setItemText(6, _translate("Setup_Window", "Black"))
        self.scolor.setItemText(7, _translate("Setup_Window", "Yellow"))
